### ISSUE TITLE
IncompatibleClassChangeError: org/eclipse/sisu/plexus/scanners/PlexusTypeVisitor

### ISSUE THREAD

**Issue by fschopp** [cloudkeeper-project/cloudkeeper#33]
The following problem has been observed when adding project `cloudkeeper-parent` as a submodule to another Maven project.

```
[INFO] --- maven-failsafe-plugin:2.17:integration-test (default) @ cloudkeeper-maven-plugin ---
[INFO] Failsafe report directory: <<removed prefix>>/cloudkeeper/cloudkeeper-maven/cloudkeeper-maven-plugin/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[3389]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running xyz.cloudkeeper.maven.ITCompileBundleMojo
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.264 sec <<< FAILURE! - in xyz.cloudkeeper.maven.ITCompileBundleMojo
testSuccessfulCompile(xyz.cloudkeeper.maven.ITCompileBundleMojo)  Time elapsed: 0.986 sec  <<< ERROR!
java.lang.IncompatibleClassChangeError: Implementing class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.eclipse.sisu.plexus.binders.PlexusAnnotatedBeanModule$PlexusSpaceModule.visitor(PlexusAnnotatedBeanModule.java:101)
    at org.eclipse.sisu.binders.SpaceModule.configure(SpaceModule.java:92)
    at org.eclipse.sisu.plexus.binders.PlexusAnnotatedBeanModule.configure(PlexusAnnotatedBeanModule.java:81)
    at org.eclipse.sisu.plexus.binders.PlexusBindingModule.configure(PlexusBindingModule.java:65)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:229)
    at com.google.inject.spi.Elements.getElements(Elements.java:103)
    at com.google.inject.spi.Elements.getElements(Elements.java:80)
    at org.eclipse.sisu.binders.WireModule.configure(WireModule.java:60)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:229)
    at com.google.inject.spi.Elements.getElements(Elements.java:103)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    at com.google.inject.Guice.createInjector(Guice.java:94)
    at com.google.inject.Guice.createInjector(Guice.java:71)
    at com.google.inject.Guice.createInjector(Guice.java:61)
    at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:476)
    at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:202)
    at org.apache.maven.plugin.testing.AbstractMojoTestCase.setupContainer(AbstractMojoTestCase.java:227)
    at org.apache.maven.plugin.testing.AbstractMojoTestCase.getContainer(AbstractMojoTestCase.java:261)
    at org.apache.maven.plugin.testing.AbstractMojoTestCase.setUp(AbstractMojoTestCase.java:115)
    at xyz.cloudkeeper.maven.ITCompileBundleMojo.setUp(ITCompileBundleMojo.java:58)

testFailedCompile(xyz.cloudkeeper.maven.ITCompileBundleMojo)  Time elapsed: 0.097 sec  <<< ERROR!
java.lang.IncompatibleClassChangeError: org/eclipse/sisu/plexus/scanners/PlexusTypeVisitor
    at org.eclipse.sisu.plexus.binders.PlexusAnnotatedBeanModule$PlexusSpaceModule.visitor(PlexusAnnotatedBeanModule.java:101)
    at org.eclipse.sisu.binders.SpaceModule.configure(SpaceModule.java:92)
    at org.eclipse.sisu.plexus.binders.PlexusAnnotatedBeanModule.configure(PlexusAnnotatedBeanModule.java:81)
    at org.eclipse.sisu.plexus.binders.PlexusBindingModule.configure(PlexusBindingModule.java:65)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:229)
    at com.google.inject.spi.Elements.getElements(Elements.java:103)
    at com.google.inject.spi.Elements.getElements(Elements.java:80)
    at org.eclipse.sisu.binders.WireModule.configure(WireModule.java:60)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:229)
    at com.google.inject.spi.Elements.getElements(Elements.java:103)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    at com.google.inject.Guice.createInjector(Guice.java:94)
    at com.google.inject.Guice.createInjector(Guice.java:71)
    at com.google.inject.Guice.createInjector(Guice.java:61)
    at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:476)
    at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:202)
    at org.apache.maven.plugin.testing.AbstractMojoTestCase.setupContainer(AbstractMojoTestCase.java:227)
    at org.apache.maven.plugin.testing.AbstractMojoTestCase.getContainer(AbstractMojoTestCase.java:261)
    at org.apache.maven.plugin.testing.AbstractMojoTestCase.setUp(AbstractMojoTestCase.java:115)
    at xyz.cloudkeeper.maven.ITCompileBundleMojo.setUp(ITCompileBundleMojo.java:58)


Results :

Tests in error: 
  ITCompileBundleMojo.setUp:58->AbstractMojoTestCase.setUp:115->AbstractMojoTestCase.getContainer:261->AbstractMojoTestCase.setupContainer:227 » IncompatibleClassChange
  ITCompileBundleMojo.setUp:58->AbstractMojoTestCase.setUp:115->AbstractMojoTestCase.getContainer:261->AbstractMojoTestCase.setupContainer:227 » IncompatibleClassChange

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] 
```

**Comment by fschopp** [comment]
An upstream bug report should be filed and linked here. Though this will have to happen later, unfortunately.

**Comment by fschopp** [comment]
See the commit message of #33 for more information.
